### ISSUE TITLE
Stabilize repository

### ISSUE THREAD

**Issue by awalone995** [NotNotTech/NotNot#1]
I feel energy emissions when reading that it's borderline fucking cargo cult code

**Comment by jasonswearingen** [comment]
code will be cleaned up prior to release.

I have been working on the rendering system: https://github.com/NotNotTech/Raylib-CsLo and with that work about done, it'll be back to the rest of the engine soon.

but it's just me, so I'll be cleaning up one it's e2e complete.  No need to have pretty code until then.

If you disagree you can elaborate on your statement.
